//This seed is how the initial product catalog was produced

module.exports = [
    {
        brand: 'Gibson',
        model: "Les Paul Standard 50's",
        color: 'Tobacco Burst',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_45721-c7246a129e0162109c331c86a57b86b1.jpg',
        price: 2699,
        category: 'guitar',
        subC1: 'electric',
        description: "The new Les Paul Standard returns to the classic design that made it relevant, played and loved -- shaping sound across generations and genres of music. It pays tribute to Gibson's Golden Era of innovation and brings authenticity back to life. The Les Paul Standard 50's has a solid mahogany body with a maple top, a rounded 50's-style mahogany neck with a rosewood fingerboard and trapezoid inlays. It's equipped with an ABR-1, the classic-style Tune-O-Matic bridge, aluminum stop bar tailpiece, vintage deluxe tuners with keystone buttons, and aged gold tophat knobs. The calibrated Burstbucker 1 (neck) and Burstbucker 2 (bridge) pickups are loaded with AlNiCo II magnets, audio taper potentiometers and orange drop capacitors."
    },
    {
        brand: 'Gibson',
        model: "Les Paul Standard 50's",
        color: 'Heritage Cherry',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_45420-b512701a572696cb951171b536a5d508.jpg',
        price: 2699,
        category: 'guitar',
        subC1: 'electric',
        description: "The new Les Paul Standard returns to the classic design that made it relevant, played and loved -- shaping sound across generations and genres of music. It pays tribute to Gibson's Golden Era of innovation and brings authenticity back to life. The Les Paul Standard 50's has a solid mahogany body with a maple top, a rounded 50's-style mahogany neck with a rosewood fingerboard and trapezoid inlays. It's equipped with an ABR-1, the classic-style Tune-O-Matic bridge, aluminum stop bar tailpiece, vintage deluxe tuners with keystone buttons, and aged gold tophat knobs. The calibrated Burstbucker 1 (neck) and Burstbucker 2 (bridge) pickups are loaded with AlNiCo II magnets, audio taper potentiometers and orange drop capacitors."
    },
    {
        brand: 'Gibson',
        model: "Les Paul Standard 50's",
        color: 'Gold Top',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_NA-5af7e7ec84485bb3d96ebbaa78675b25.jpg',
        price: 2699,
        category: 'guitar',
        subC1: 'electric',
        description: "The new Les Paul Standard returns to the classic design that made it relevant, played and loved -- shaping sound across generations and genres of music. It pays tribute to Gibson's Golden Era of innovation and brings authenticity back to life. The Les Paul Standard 50's has a solid mahogany body with a maple top, a rounded 50's-style mahogany neck with a rosewood fingerboard and trapezoid inlays. It's equipped with an ABR-1, the classic-style Tune-O-Matic bridge, aluminum stop bar tailpiece, vintage deluxe tuners with keystone buttons, and aged gold tophat knobs. The calibrated Burstbucker 1 (neck) and Burstbucker 2 (bridge) pickups are loaded with AlNiCo II magnets, audio taper potentiometers and orange drop capacitors."
    },
    {
        brand: 'Gibson',
        model: "Les Paul Standard 50's P90",
        color: 'Gold Top',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_NA-e9904fab4638a4a340ca67088d7e018d.jpg',
        price: 2699,
        category: 'guitar',
        subC1: 'electric',
        description: "The new Les Paul Standard returns to the classic design that made it relevant, played and loved -- shaping sound across generations and genres of music. It pays tribute to Gibson's Golden Era of innovation and brings authenticity back to life. The Les Paul Standard 50's has a solid mahogany body with a maple top, a rounded 50's-style mahogany neck with a rosewood fingerboard and trapezoid inlays. It's equipped with an ABR-1, the classic-style Tune-O-Matic bridge, aluminum stop bar tailpiece, vintage deluxe tuners with keystone buttons, and aged gold tophat knobs. The calibrated Burstbucker 1 (neck) and Burstbucker 2 (bridge) pickups are loaded with AlNiCo II magnets, audio taper potentiometers and orange drop capacitors."
    },
    {
        brand: 'Gibson',
        model: "Les Paul Standard 60's", 
        color: 'Iced Tea',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_45381-1b55f2d993e817fcf170dbc273a56b1c.jpg',
        price: 2699,
        category: 'guitar',
        subC1: 'electric',
        description: "The new Les Paul Standard returns to the classic design that made it relevant, played and loved -- shaping sound across generations and genres of music. It pays tribute to Gibson's Golden Era of innovation and brings authenticity back to life. The Les Paul Standard 60's has a solid mahogany body with an AA figured maple top, and a slim taper 60's-style mahogany neck with a rosewood fingerboard and trapezoid inlays. It's equipped with a classic-style Tune-O-Matic bridge, aluminum stop bar tailpiece, Grover Rotomatic 'Kidney' tuners, and gold top hat knobs with silver reflectors. The Burstbucker 61R (neck) Burstbucker 61T (bridge) pickups are loaded with AlNiCo V magnets, audio taper potentiometers and orange drop capacitors."
    },
    {
        brand: 'Gibson',
        model: "Les Paul Standard 60's", 
        color: 'Bourbon Burst',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_45371-63632c6a87b4ffe9853b9902f0069020.jpg',
        price: 2699,
        category: 'guitar',
        subC1: 'electric',
        description: "The new Les Paul Standard returns to the classic design that made it relevant, played and loved -- shaping sound across generations and genres of music. It pays tribute to Gibson's Golden Era of innovation and brings authenticity back to life. The Les Paul Standard 60's has a solid mahogany body with an AA figured maple top, and a slim taper 60's-style mahogany neck with a rosewood fingerboard and trapezoid inlays. It's equipped with a classic-style Tune-O-Matic bridge, aluminum stop bar tailpiece, Grover Rotomatic 'Kidney' tuners, and gold top hat knobs with silver reflectors. The Burstbucker 61R (neck) Burstbucker 61T (bridge) pickups are loaded with AlNiCo V magnets, audio taper potentiometers and orange drop capacitors."
    },
    {
        brand: 'Gibson',
        model: "Les Paul Standard 60's", 
        color: 'Unburst',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_45669-03eacba3a28367537a07d096987f41d4.jpg',
        price: 2699,
        category: 'guitar',
        subC1: 'electric',
        description: "The new Les Paul Standard returns to the classic design that made it relevant, played and loved -- shaping sound across generations and genres of music. It pays tribute to Gibson's Golden Era of innovation and brings authenticity back to life. The Les Paul Standard 60's has a solid mahogany body with an AA figured maple top, and a slim taper 60's-style mahogany neck with a rosewood fingerboard and trapezoid inlays. It's equipped with a classic-style Tune-O-Matic bridge, aluminum stop bar tailpiece, Grover Rotomatic 'Kidney' tuners, and gold top hat knobs with silver reflectors. The Burstbucker 61R (neck) Burstbucker 61T (bridge) pickups are loaded with AlNiCo V magnets, audio taper potentiometers and orange drop capacitors."
    },
    {
        brand: 'Gibson',
        model: 'Slash Les Paul Standard', 
        color: 'Anaconda Burst',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_45716-8147d77f194f67547da9e6fe6d618dce.jpg',
        price: 2999,
        category: 'guitar',
        subC1: 'electric',
        description: "Gibson and Slash are proud to present the Slash Collection Gibson Les Paul Standard. It represents influential Gibson guitars Slash has used during his career, inspiring multiple generations of players around the world. The Slash Collection of Gibson guitars can be seen live on stage with Slash today. Each Slash Collection Gibson Les Paul™ Standard features a AAA flamed maple top, a solid mahogany body, and Slash’s personal touches including a 50s neck profile, Gibson Custom BurstBucker® Alnico 2 pickups, color-coordinated hardware appointments, hand-wired electronics with Orange Drop® capacitors, and a vintage-style brown hardshell case. Exclusive to the Slash Collection are Slash’s “Skully” signature drawing on the back of the headstock, Slash’s signature on the truss rod cover, a blank truss rod cover in the case, Slash-approved Ernie Ball® strings, and four Slash Jim Dunlop Tortex® picks. The Slash Gibson Les Paul Standard is available in Vermillion Burst and Anaconda Burst."
    },
    {
        brand: 'Gibson',
        model: 'Slash Les Paul Standard', 
        color: 'November Burst',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_45221-fa0ac9a51dbe0d998e6a29618ddb0811.jpg',
        price: 2999,
        category: 'guitar',
        subC1: 'electric',
        description: "Gibson and Slash are proud to present the Slash Collection Gibson Les Paul™ Standard. It represents influential Gibson guitars Slash has used during his career, inspiring multiple generations of players around the world. The Slash Collection of Gibson guitars can be seen live on stage with Slash today. Each Slash Collection Gibson Les Paul Standard features a AAA flamed maple top, a solid mahogany body, and Slash’s personal touches including a 50s neck profile, Gibson Custom BurstBucker™ Alnico 2 pickups, color-coordinated hardware appointments, hand-wired electronics with Orange Drop® capacitors, and a vintage-style brown hardshell case. Exclusive to the Slash Collection are Slash’s “Skully” signature drawing on the back of the headstock, Slash’s signature on the truss rod cover, a blank truss rod cover in the case, Slash-approved Ernie Ball® strings, and four Slash Jim Dunlop Tortex® picks. The Slash Les Paul Standard is available in November Burst and Appetite Burst."
    },
    {
        brand: 'Gibson',
        model: 'Slash Les Paul Standard', 
        color: 'Appetite Amber',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_45687-df943b836ccd50fae24080019512d7ee.jpg',
        price: 2999,
        category: 'guitar',
        subC1: 'electric',
        description: "Gibson and Slash are proud to present the Slash Collection Gibson Les Paul™ Standard. It represents influential Gibson guitars Slash has used during his career, inspiring multiple generations of players around the world. The Slash Collection of Gibson guitars can be seen live on stage with Slash today. Each Slash Collection Gibson Les Paul Standard features a AAA flamed maple top, a solid mahogany body, and Slash’s personal touches including a 50s neck profile, Gibson Custom BurstBucker™ Alnico 2 pickups, color-coordinated hardware appointments, hand-wired electronics with Orange Drop® capacitors, and a vintage-style brown hardshell case. Exclusive to the Slash Collection are Slash’s “Skully” signature drawing on the back of the headstock, Slash’s signature on the truss rod cover, a blank truss rod cover in the case, Slash-approved Ernie Ball® strings, and four Slash Jim Dunlop Tortex® picks. The Slash Les Paul Standard is available in November Burst and Appetite Burst."
    },
    {
        brand: 'Gibson',
        model: 'Slash Les Paul Standard', 
        color: 'Vermillion Burst',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_45682-48ddbebb7c79833cbe002e6239a54a59.jpg',
        price: 2999,
        category: 'guitar',
        subC1: 'electric',
        description: "Gibson and Slash are proud to present the Slash Collection Gibson Les Paul™ Standard. It represents influential Gibson guitars Slash has used during his career, inspiring multiple generations of players around the world. The Slash Collection of Gibson guitars can be seen live on stage with Slash today. Each Slash Collection Gibson Les Paul Standard features a AAA flamed maple top, a solid mahogany body, and Slash’s personal touches including a 50s neck profile, Gibson Custom BurstBucker™ Alnico 2 pickups, color-coordinated hardware appointments, hand-wired electronics with Orange Drop® capacitors, and a vintage-style brown hardshell case. Exclusive to the Slash Collection are Slash’s “Skully” signature drawing on the back of the headstock, Slash’s signature on the truss rod cover, a blank truss rod cover in the case, Slash-approved Ernie Ball® strings, and four Slash Jim Dunlop Tortex® picks. The Slash Les Paul Standard is available in November Burst and Appetite Burst."
    },
    {
        brand: 'Fender',
        model: 'American Pro Stratocaster', 
        color: '3-Color Sunburst',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_NA-af9df8291d3e1dee80e2f3f98a016fe8.jpg',
        price: 1699,
        category: 'guitar',
        subC1: 'electric',
        description: "The American Professional II Stratocaster® draws from more than sixty years of innovation, inspiration and evolution to meet the demands of today’s working player. Our popular Deep 'C' neck now sports smooth rolled fingerboard edges, a 'Super-Natural' satin finish and a newly sculpted neck heel for a supremely comfortable feel and easy access to the upper register. New V-Mod II Stratocaster single-coil pickups are more articulate than ever while retaining bell-like chime and warmth. An upgraded 2-point tremolo with a cold-rolled steel block increases sustain, clarity and high-end sparkle. The American Pro II Stratocaster delivers instant familiarity and sonic versatility you’ll feel and hear right away, with broad ranging improvements that add up to nothing less than a new standard for professional instruments.",
    },
    {
        brand: 'Fender',
        model: 'Player Stratocaster', 
        color: 'Buttercream',
        image: 'https://c1.zzounds.com/media/productmedia/fit,600by800/quality,85/1_Full_Straight_Front_NA-e05e413006e61f7d9a156bcd1b8e56f3.jpg',
        price: 849,
        category: 'guitar',
        subC1: 'electric',
        description: "The inspiring sound of a Stratocaster is one of the foundations of Fender. Featuring this classic sound -- bell-like high end, punchy mids and robust low end, combined with crystal-clear articulation -- the Player Stratocaster is packed with authentic Fender feel and style. It's ready to serve your musical vision, it's versatile enough to handle any style of music and it's the perfect platform for creating your own sound. Respecting our heritage while maintaining our innovative spirit, the power trio of Player Series single-coil pickups are crisp and articulate -- it's authentic Fender tone with a modern edge. The \'Modern C\'-shaped maple neck\'s comfortable contours and smooth finish are ideal for almost any playing style. By adding a 22nd medium jumbo fret to the contemporary 9.5in.-radius fingerboard, Fender\'s made it easier to express yourself musically. The updated 2-point tremolo design has smoother travel for enhanced playing feel while simultaneously giving you rock-solid tuning stability since there\'s less friction against the posts. Other features include master volume and tone controls, a 5-way pickup switch, 3-ply pickguard, synthetic bone nut, dual-wing string tree, sealed tuning machines and four-bolt \'F\'-stamped neck plate that marks this instrument as the real deal -- as Fender as it gets.",
    },
    {
        brand: 'Fender',
        model: 'Player Plus Stratocaster HSS', 
        color: 'Silverburst',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/0147323391_fen_ins_frt_1_rr_839019-0fe46ce1e59235e631d2722a3094b428.jpg',
        price: 1129,
        category: 'guitar',
        subC1: 'electric',
        description: "Fusing classic Fender design with player-centric features and exciting new finishes, the Player Plus Stratocaster HSS delivers superb playability and unmistakable style. The powerful Player Plus humbucking pickup delivers the perfect balance of gain and definition, while the Player Plus Noiseless Strat pickups are bright and touch sensitive, offering classic Strat tone without hum. A push-pull tone controls activate coil-split mode for the humbucking pickup, delivering crystal-clear single-coil tones. The silky satin Modern 'C' Player Plus Strat neck fits your hand like a glove, with smooth rolled edges for supreme comfort. The 12\" radius fingerboard and 22 medium jumbo frets facilitate fluid leads and choke free bends. Smooth and responsive, the 2-point tremolo provides classic vibrato effects, while the locking tuners provide rock-solid tuning and make string changes quick and easy."
    },
    {
        brand: 'Fender',
        model: 'Player Plus Telecaster', 
        color: 'Cosmic Jade',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/0147332376_fen_ins_frt_1_rr_839028-b8157a092eaf617a6e57c57b429e0169.jpg',
        price: 1099,
        category: 'guitar',
        subC1: 'electric',
        description: "Fusing classic Fender® design with player-centric features and exciting new finishes, the Player Plus Telecaster® delivers superb playability and unmistakable style. Powered by a set of Player Plus Noiseless™ pickups, the Player Plus Tele® delivers warm, sweet Tele® twang – without hum. A push-pull switch on the tone control engages both pickups in series operation, delivering increased output and body. The silky satin Modern “C” Player Plus Tele® neck fits your hand like a glove, with smooth rolled edges for supreme comfort. The 12” radius fingerboard and 22 medium jumbo frets facilitate fluid leads and choke free bends. A modern 6-saddle Tele bridge with block steel saddles adds a touch of brightness while providing precise intonation and the locking tuners provide rock-solid tuning and make string changes quick and easy. With classic Fender style, advanced features and stunning new finishes, the Player Plus Telecaster is the perfect tool to spark your creativity and stand out from the crowd."
    },
    {
        brand: 'EVH',
        model: 'Striped Series', 
        color: 'Black and Yellow',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_NA-fec262a690085c244e978643faca3ac1.jpg',
        price: 1149,
        category: 'guitar',
        subC1: 'electric',
        description: 'With a career of being copied, the EVH Striped Series guitars put Eddie Van Halen\'s historic and authentic style in your hands ... These are high powered, high-performance machines as kickbutt to look at as they are to play. The Striped Series guitar features a basswood Stratocaster®-style body decked out in Eddie\'s famed striped graphics — Red with Black Stripes, Black with Yellow Stripes and White with Black Stripes. These unique guitars also have a graphite-reinforced bolt-on quartersawn maple neck with a hand-rubbed oil finish on the back, 12"-16" maple fingerboard with 22 jumbo frets and black dot inlays and a thumbwheel truss rod adjustment wheel for convenient neck relief tweaks.'
    }, 

    {
        brand: 'Fender',
        model: 'Deluxe Active Precision Special PF', 
        color: 'Olympic White',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_NA-d1a559c21305e194e7e8541f1f52343a.jpg',
        price: 999,
        category: 'bass',
        subC1: 'electric',
        
    },
    {
        brand: 'Gibson',
        model: 'Les Paul Jr Tribute DC',
        color: 'Blue Satin',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_NA-3d1c05d5ab48bed0f9f86b90df4f8c4b.jpg',
        price: 999,
        category: 'bass',
        subC1: 'electric',
    },
    {
        brand: 'Fender',
        model: 'American Pro II Precision',
        color: '3-Color Sunburst',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_NA-d09f2756857067f64b226cb089112c77.jpg',
        price: 1749,
        category: 'bass',
        subC1: 'electric',
    },
    {
        brand: 'Fender',
        model: 'Player Plus Precision',
        color: 'Cosmic Jade',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/0147362376_fen_ins_frt_1_rr_839049-1ee770c970d17c39e8a2671e71423f0c.jpg',
        price: 1749,
        category: 'bass',
        subC1: 'electric',
    }, 
    {
        brand: 'Gibson',
        model: 'SG Standard',
        color: 'Ebony',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_NA-380518568edbacc9496b6f2e76bce140.jpg',
        price: 1599,
        category: 'bass',
        subC1: 'electric',
        description: "The SG Bass has the legendary looks, sound and feel which made it one of Gibson's most iconic basses. The short scale length is actually a big part of this sound! While the short scale length of the SG Bass is preferred by smaller players, it's also preferred by many for the strong fundamental tone for which this short scale bass is known. As expected, the solid mahogany body has deeply sculpted scarfing and the rounded profile mahogany neck and rosewood fingerboard feels familiar and comfortable. A pair of calibrated SG bass pickups (neck and bridge) with individual volume and master tone controls add further tonal possibilities."
    }, 
    {
        brand: 'Ibanez',
        model: 'SRMS805 Bass',
        color: 'Brown Topaz Burst',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_NA-0193ba1c5371a590925df29191496d75.jpg',
        price: 999,
        category: 'bass',
        subC1: 'electric',
        description: "The Ibanez SRMS805 Bass Workshop Multi-Scale 5-String Electric Bass is a quality instrument designed for the experienced, seasoned musician. Its Poplar burl / Mahogany body is attached to a 5-piece Jatoba/Walnut SRMS4 neck with a Panga Panga fretboard, Medium frets and custom multi-scale inlays. The Mono-Rail VS Bridge is the perfect match for a fan-fret instrument, allowing for independent positioning of each strings “mini-bridge” section to providing excellent intonation and superior string vibration transference. Electronics include Bartolini® BH2-4 pickups, for a full range warm punchy tone, and a 3-band EQ w/ Bypass switch and Mid-Frequency switch for complete sonic control.",
    }, 

    {
        brand: 'Dunlop',
        model: 'Original Crybaby Wah Pedal',
        color: 'Black',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/Crybaby2web-00cdea49c29aabbd2a4c2c69a46b17e3.jpg',
        price: 89,
        category: 'effects',
        subC1: 'filter',
        description: "If it ain't broke, don't fix it. The Dunlop Crybaby Wah-Wah has stood the test of time and has served generations of guitarists of every style. The sound is unmistakable, and frankly, has never been duplicated. There is but one control, the pedal itself - that is all you need to add this classic sound to your own. Mash the pedal down and the effect kicks in. Mash it again and you've engaged the bypass and your pure signal passes through."
    },
    {
        brand: 'MXR',
        model: 'EVH Phase 90 Phaser Pedal',
        color: 'Red, White, and Black',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/DUN-EVH90-c47c525b18b978023c924c8efe330f41.jpg',
        price: 129,
        category: 'effects',
        subC1: 'modulation',
        description: "MXR has taken their Phase 90 pedal design and brought a little EVH flavor to the table with the hypnotic-sounding EVH90 Van Halen Phase 90 pedal. Unchain your signal for a whirlwind of mind-spinning phase modulation via one simple speed control knob. A script switch allows you to toggle between a vintage 'Script Logo' phase tone and a more modern 'Block Logo' phase effect. A secure outer chassis keeps your signal ready to rock stomp after stomp, and it's dressed to kill in Van Halen's iconic striped 'Frankenstein' graphics. This simple effects pedal will spin your tone at mesmerizing velocities, captivating listeners in assured Van Halen style.",
    },
    {
        brand: 'Boss',
        model: 'RC-1 Loop Station',
        color: 'Red',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/rc-1_top_gal-b35bbb514f2497b72d2d7c27e0e3f3df.jpg',
        price: 105,
        category: 'effects',
        subC1: 'loop',
        description: "The BOSS RC-1 is the simplest and most user-friendly Loop Station ever, and it's a ton of fun! Since the RC-20 Loop Station was first released in 2001, BOSS has led the way by continually releasing looping products. Though they've been used and enjoyed by various looping artists and performers, BOSS still pursued an easier and more affordable solution. The RC-1 is a straightforward looper that is easy to operate. Experience the fun of looping when you record, playback, overdub, and undo or redo loops using this compact BOSS stompbox.",
    },
    {
        brand: 'JHS',
        model: 'Bonsai Screamer Overdrive',
        color: 'Green',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/BONSAI-08499de6df01b3636da2342037c70208.jpg',
        price: 249,
        category: 'effects',
        subC1: 'distortion',
        description: "In the late 1970's the overdrive pedal was arguably perfected when Japanese engineers designed the sound that we now know as the heart and soul of so many of our favorite artists, recordings and sounds. Players ranging from The Edge, Trey Anastasio, Buddy Guy, Kirk Hammett, John Mayer, SRV, Carlos Santana and thousands more from every possible genre have utilized and depended on this classic iconic green box. If a single effect pedal was chosen to board a Voyager 3 mission and be solely responsible for showing the universe the sound of overdrive, it would undoubtedly be the Tube Screamer. It is probably the most produced and sold pedal in the history of guitar pedals! The Bonsai is our tribute to one of the greatest pedals ever created.",
    },
    {
        brand: 'Pro Co',
        model: 'RAT2 Distortion',
        color: 'Black',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/Rat2_front_lg-fd7d7cde74fdb21324648b9085fc8e75.jpg',
        price: 69,
        category: 'effects',
        subC1: 'distortion',
        description: "Do you straddle the fine line between the traditional guitarist and the constant innovator? Are you just as comfortable laying back in the pocket as you are taking a solo with a foot up on the monitor? If this sounds like you, The RAT 2 will be your go-to distortion pedal for every gig, whether it's rock, blues, punk, or jazz. This is the classic RAT tone. The standard that all other distortion devices are measured against. Heard on thousands of recordings, it has helped define the sound of the past three decades' most influential bands."
    },
]