module.exports = [
    {
        brand: 'Gibson',
        model: "Les Paul Standard 50's",
        color: 'Tobacco Burst',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_45721-c7246a129e0162109c331c86a57b86b1.jpg',
        price: 2699,
        category: 'guitar',
        subC1: 'electric',
        description: "The new Les Paul Standard returns to the classic design that made it relevant, played and loved -- shaping sound across generations and genres of music. It pays tribute to Gibson's Golden Era of innovation and brings authenticity back to life. The Les Paul Standard 50's has a solid mahogany body with a maple top, a rounded 50's-style mahogany neck with a rosewood fingerboard and trapezoid inlays. It's equipped with an ABR-1, the classic-style Tune-O-Matic bridge, aluminum stop bar tailpiece, vintage deluxe tuners with keystone buttons, and aged gold tophat knobs. The calibrated Burstbucker 1 (neck) and Burstbucker 2 (bridge) pickups are loaded with AlNiCo II magnets, audio taper potentiometers and orange drop capacitors."
    },
    {
        brand: 'Gibson',
        model: "Les Paul Standard 60's", 
        color: 'Iced Tea',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_45381-1b55f2d993e817fcf170dbc273a56b1c.jpg',
        price: 2699,
        category: 'guitar',
        subC1: 'electric',
        description: "The new Les Paul Standard returns to the classic design that made it relevant, played and loved -- shaping sound across generations and genres of music. It pays tribute to Gibson's Golden Era of innovation and brings authenticity back to life. The Les Paul Standard 60's has a solid mahogany body with an AA figured maple top, and a slim taper 60's-style mahogany neck with a rosewood fingerboard and trapezoid inlays. It's equipped with a classic-style Tune-O-Matic bridge, aluminum stop bar tailpiece, Grover Rotomatic 'Kidney' tuners, and gold top hat knobs with silver reflectors. The Burstbucker 61R (neck) Burstbucker 61T (bridge) pickups are loaded with AlNiCo V magnets, audio taper potentiometers and orange drop capacitors."
    },
    {
        brand: 'Fender',
        model: 'American Pro Stratocaster', 
        color: '3-Color Sunburst',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_NA-af9df8291d3e1dee80e2f3f98a016fe8.jpg',
        price: 1699,
        category: 'guitar',
        subC1: 'electric',
        description: "The American Professional II Stratocaster® draws from more than sixty years of innovation, inspiration and evolution to meet the demands of today’s working player. Our popular Deep 'C' neck now sports smooth rolled fingerboard edges, a 'Super-Natural' satin finish and a newly sculpted neck heel for a supremely comfortable feel and easy access to the upper register. New V-Mod II Stratocaster single-coil pickups are more articulate than ever while retaining bell-like chime and warmth. An upgraded 2-point tremolo with a cold-rolled steel block increases sustain, clarity and high-end sparkle. The American Pro II Stratocaster delivers instant familiarity and sonic versatility you’ll feel and hear right away, with broad ranging improvements that add up to nothing less than a new standard for professional instruments.",
    },
    {
        brand: 'Gibson',
        model: 'Slash Les Paul Standard', 
        color: 'Anaconda Burst',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_45716-8147d77f194f67547da9e6fe6d618dce.jpg',
        price: 2999,
        category: 'guitar',
        subC1: 'electric',
        description: "Gibson and Slash are proud to present the Slash Collection Gibson Les Paul Standard. It represents influential Gibson guitars Slash has used during his career, inspiring multiple generations of players around the world. The Slash Collection of Gibson guitars can be seen live on stage with Slash today. Each Slash Collection Gibson Les Paul™ Standard features a AAA flamed maple top, a solid mahogany body, and Slash’s personal touches including a 50s neck profile, Gibson Custom BurstBucker® Alnico 2 pickups, color-coordinated hardware appointments, hand-wired electronics with Orange Drop® capacitors, and a vintage-style brown hardshell case. Exclusive to the Slash Collection are Slash’s “Skully” signature drawing on the back of the headstock, Slash’s signature on the truss rod cover, a blank truss rod cover in the case, Slash-approved Ernie Ball® strings, and four Slash Jim Dunlop Tortex® picks. The Slash Gibson Les Paul Standard is available in Vermillion Burst and Anaconda Burst."
    },
    {
        brand: 'Gibson',
        model: 'Slash Les Paul Standard', 
        color: 'November Burst',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_45221-fa0ac9a51dbe0d998e6a29618ddb0811.jpg',
        price: 2999,
        category: 'guitar',
        subC1: 'electric',
        description: "Gibson and Slash are proud to present the Slash Collection Gibson Les Paul™ Standard. It represents influential Gibson guitars Slash has used during his career, inspiring multiple generations of players around the world. The Slash Collection of Gibson guitars can be seen live on stage with Slash today. Each Slash Collection Gibson Les Paul Standard features a AAA flamed maple top, a solid mahogany body, and Slash’s personal touches including a 50s neck profile, Gibson Custom BurstBucker™ Alnico 2 pickups, color-coordinated hardware appointments, hand-wired electronics with Orange Drop® capacitors, and a vintage-style brown hardshell case. Exclusive to the Slash Collection are Slash’s “Skully” signature drawing on the back of the headstock, Slash’s signature on the truss rod cover, a blank truss rod cover in the case, Slash-approved Ernie Ball® strings, and four Slash Jim Dunlop Tortex® picks. The Slash Les Paul Standard is available in November Burst and Appetite Burst."
    },
    {
        brand: 'Fender',
        model: 'Player Plus Telecaster', 
        color: 'Cosmic Jade',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/0147332376_fen_ins_frt_1_rr_839028-b8157a092eaf617a6e57c57b429e0169.jpg',
        price: 1099,
        category: 'guitar',
        subC1: 'electric',
        description: "Fusing classic Fender® design with player-centric features and exciting new finishes, the Player Plus Telecaster® delivers superb playability and unmistakable style. Powered by a set of Player Plus Noiseless™ pickups, the Player Plus Tele® delivers warm, sweet Tele® twang – without hum. A push-pull switch on the tone control engages both pickups in series operation, delivering increased output and body. The silky satin Modern “C” Player Plus Tele® neck fits your hand like a glove, with smooth rolled edges for supreme comfort. The 12” radius fingerboard and 22 medium jumbo frets facilitate fluid leads and choke free bends. A modern 6-saddle Tele bridge with block steel saddles adds a touch of brightness while providing precise intonation and the locking tuners provide rock-solid tuning and make string changes quick and easy. With classic Fender style, advanced features and stunning new finishes, the Player Plus Telecaster is the perfect tool to spark your creativity and stand out from the crowd."
    },
    {
        brand: 'EVH',
        model: 'Striped Series', 
        color: 'Black and Yellow',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_NA-fec262a690085c244e978643faca3ac1.jpg',
        price: 1149,
        category: 'guitar',
        subC1: 'electric',
        description: 'With a career of being copied, the EVH Striped Series guitars put Eddie Van Halen\'s historic and authentic style in your hands ... These are high powered, high-performance machines as kickbutt to look at as they are to play. The Striped Series guitar features a basswood Stratocaster®-style body decked out in Eddie\'s famed striped graphics — Red with Black Stripes, Black with Yellow Stripes and White with Black Stripes. These unique guitars also have a graphite-reinforced bolt-on quartersawn maple neck with a hand-rubbed oil finish on the back, 12"-16" maple fingerboard with 22 jumbo frets and black dot inlays and a thumbwheel truss rod adjustment wheel for convenient neck relief tweaks.'
    }, 
    {
        brand: 'Fender',
        model: 'Deluxe Active Precision Special PF', 
        color: 'Olympic White',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_NA-d1a559c21305e194e7e8541f1f52343a.jpg',
        price: 999,
        category: 'bass',
        subC1: 'electric',
        
    },
    {
        brand: 'Gibson',
        model: 'Les Paul Jr Tribute DC',
        color: 'Blue Satin',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_NA-3d1c05d5ab48bed0f9f86b90df4f8c4b.jpg',
        price: 999,
        category: 'bass',
        subC1: 'electric',
    },
    {
        brand: 'Fender',
        model: 'American Pro II Precision',
        color: '3-Color Sunburst',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/1_Full_Straight_Front_NA-d09f2756857067f64b226cb089112c77.jpg',
        price: 1749,
        category: 'bass',
        subC1: 'electric',
    },
    {
        brand: 'Fender',
        model: 'Player Plus Precision',
        color: 'Cosmic Jade',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/0147362376_fen_ins_frt_1_rr_839049-1ee770c970d17c39e8a2671e71423f0c.jpg',
        price: 1749,
        category: 'bass',
        subC1: 'electric',
    }, 
    {
        brand: 'Dunlop',
        model: 'Original Crybaby Wah Pedal',
        color: 'Black',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/Crybaby2web-00cdea49c29aabbd2a4c2c69a46b17e3.jpg',
        price: 89,
        category: 'effects',
        subC1: 'filter',
    },
    {
        brand: 'MXR',
        model: 'EVH Phase 90 Phaser Pedal',
        color: 'Red, White, and Black',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/DUN-EVH90-c47c525b18b978023c924c8efe330f41.jpg',
        price: 129,
        category: 'effects',
        subC1: 'modulation',
    },
    {
        brand: 'Boss',
        model: 'RC-1 Loop Station',
        color: 'Red',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/rc-1_top_gal-b35bbb514f2497b72d2d7c27e0e3f3df.jpg',
        price: 105,
        category: 'effects',
        subC1: 'loop',
    },
    {
        brand: 'JHS',
        model: 'Bonsai Screamer Overdrive',
        color: 'Green',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/BONSAI-08499de6df01b3636da2342037c70208.jpg',
        price: 249,
        category: 'effects',
        subC1: 'distortion',
    },
    {
        brand: 'Pro Co',
        model: 'RAT2 Distortion',
        color: 'Black',
        image: 'https://c1.zzounds.com/media/productmedia/fit,2018by3200/quality,85/Rat2_front_lg-fd7d7cde74fdb21324648b9085fc8e75.jpg',
        price: 69,
        category: 'effects',
        subC1: 'distortion',
    },
]